version: '3'
services:
  frontend:
    build: ./todolist
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always

  backend:
    build: ./Server
    ports:
      - "301:301"
    restart: always

