# Get the base image 
FROM node:20-alpine

# Set the working directory
WORKDIR /app 

#Copy the package.json and package-lock.json files 
COPY package*.json ./

# Install dependencies 
RUN npm install 

# Copy the source code 
COPY . .

# Expose the port 
EXPOSE 5173

# Start the application 
CMD ["npm","run","dev"]


